language: python
python:
  - "2.7"
install: "pip install pyang requests"
script:
  - ./vendor/cisco/check.sh
  - ./standard/ietf/check.sh
  - ./standard/bbf/check.sh
  - ./experimental/ieee/check.sh

