sudo: required
dist: trusty
language: python
python:
  - "2.7"
before_install:
  - wget -nv https://download.opensuse.org/repositories/home:liberouter/xUbuntu_14.04/Release.key -O Release.key
  - sudo apt-key add - < Release.key
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/liberouter/xUbuntu_14.04/ /' > /etc/apt/sources.list.d/libyang.list"
  - sudo apt-get update
  - sudo apt-get install libyang
install: "pip install pyang==1.7.3 requests"
notifications:
  webhooks:
    urls:
      - https://yangcatalog.org/api/checkComplete
      - https://yang.amsl.com/api/checkComplete
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always
script:
  - travis_wait 30 ./vendor/cisco/check.sh
  - ./standard/ietf/check.sh
  - ./standard/bbf/check.sh
  - ./experimental/ieee/check.sh
  - ./standard/ieee/check.sh
