language: python
python:
  - "2.7"
install: "pip install pyang==1.7.1 requests"
notifications:
  webhooks:
    urls:
      - https://yangcatalog.org:8443/checkComplete
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always
script:
  - travis_wait 30 ./vendor/cisco/check.sh
  - ./standard/ietf/check.sh
  - ./standard/bbf/check.sh
  - ./experimental/ieee/check.sh
  - ./standard/ieee/check.sh
